const APP_KEY="gym_note_data",VERSION=3;
const TEMPLATE={dataVersion:3,configured:false,goals:{weight:null,fat:null,muscle:null,restSeconds:60},zeroi:[
{id:"shoulder_elevation",name:"Shoulder Elevation",jp:"ショルダー・エレベーション",target:"背中上部・肩まわり",reps:10,icon:"🙆"},
{id:"chest_extension",name:"Chest Extension",jp:"チェスト・エクステンション",target:"胸部・肩",reps:10,icon:"🫸"},
{id:"adductor_extension",name:"Adductor Extension",jp:"アダクター・エクステンション",target:"股関節まわり",reps:10,icon:"🦵"},
{id:"hip_flex",name:"Hip Flex",jp:"ヒップ・フレックス",target:"臀部・お尻",reps:10,icon:"🍑"}],
exercises:[
{id:"legpress",name:"レッグプレス",icon:"🦵",weight:45,reps:10,sets:2,step:5,note:"脚・お尻。膝を伸ばし切らない。"},
{id:"chest",name:"チェストプレス",icon:"💪",weight:20,reps:10,sets:2,step:2.5,note:"胸。肩をすくめずゆっくり。"},
{id:"lat",name:"ラットプルダウン",icon:"↙️",weight:22.5,reps:10,sets:2,step:2.5,note:"背中。胸の上へ引く。"},
{id:"row",name:"シーテッドロー",icon:"🚣",weight:22.5,reps:10,sets:2,step:2.5,note:"背中。肩甲骨を寄せる。"},
{id:"legcurl",name:"レッグカール",icon:"🦿",weight:17.5,reps:10,sets:2,step:2.5,note:"もも裏。反動を使わない。"},
{id:"abductor",name:"ヒップアブダクター",icon:"🍑",weight:22.5,reps:12,sets:2,step:2.5,note:"お尻の横。開いて1秒止める。"},
{id:"abs",name:"アブドミナルクランチ",icon:"🔥",weight:17.5,reps:12,sets:2,step:2.5,note:"腹筋。首ではなく腹を丸める。"}],body:[],history:[]};
const clone=x=>JSON.parse(JSON.stringify(x)),fmt=n=>n==null?"—":(Number.isInteger(Number(n))?String(Number(n)):Number(n).toFixed(1));
function migrate(x){const s=clone(TEMPLATE);if(!x||typeof x!=="object")return s;Object.assign(s,x);s.dataVersion=VERSION;s.goals=Object.assign({},TEMPLATE.goals,x.goals||{});s.zeroi=x.zeroi?.length?x.zeroi:clone(TEMPLATE.zeroi);s.exercises=x.exercises?.length?x.exercises:clone(TEMPLATE.exercises);s.body=Array.isArray(x.body)?x.body:[];s.history=Array.isArray(x.history)?x.history.map(h=>Object.assign({zeroi:[]},h)):[];s.configured=true;return s}
function load(){try{const x=JSON.parse(localStorage.getItem(APP_KEY));return x?migrate(x):clone(TEMPLATE)}catch(e){return clone(TEMPLATE)}}function save(){localStorage.setItem(APP_KEY,JSON.stringify(state))}
let state=load(),session=newSession(),timerI=null,installPrompt=null;
function newSession(){const sets={};state.exercises.forEach(e=>sets[e.id]=Array(e.sets).fill(false));const z={};state.zeroi.forEach(x=>z[x.id]=false);return{sets,zeroi:z,efforts:{},warmup:false,cardio:false,vibration:false,cardioType:"walk"}}
function toast(t){const x=document.getElementById("toast");x.textContent=t;x.classList.add("show");setTimeout(()=>x.classList.remove("show"),1800)}
function page(id){document.querySelectorAll(".page").forEach(x=>x.classList.toggle("active",x.id===id));document.querySelectorAll(".nav").forEach(x=>x.classList.toggle("active",x.dataset.page===id));window.scrollTo(0,0);if(id==="history")renderHistory();if(id==="body")renderBody();if(id==="settings")renderSettings()}
document.querySelectorAll(".nav").forEach(b=>b.onclick=()=>page(b.dataset.page));document.querySelectorAll("[data-page-go]").forEach(b=>b.onclick=()=>page(b.dataset.pageGo));
function renderToday(){const d=new Date(),w="日月火水木金土"[d.getDay()];todayDate.textContent=`${d.getFullYear()}年${d.getMonth()+1}月${d.getDate()}日（${w}）`;setupNotice.hidden=state.configured;
zeroList.innerHTML=state.zeroi.map((z,i)=>`<div class="card row"><div class="exerciseTitle"><span class="icon">${z.icon}</span><div><strong>${i+1}. ${z.name}</strong><small>${z.jp} / ${z.target}<br>ゆっくり ${z.reps}回</small></div></div><button class="done ${session.zeroi[z.id]?"on":""}" data-zero="${z.id}">${session.zeroi[z.id]?"完了 ✓":"完了"}</button></div>`).join("");
document.querySelectorAll("[data-zero]").forEach(b=>b.onclick=()=>{session.zeroi[b.dataset.zero]=!session.zeroi[b.dataset.zero];renderToday()});
exerciseList.innerHTML=state.exercises.map((e,i)=>{const all=session.sets[e.id].every(Boolean),ef=session.efforts[e.id]||"",next=all&&ef==="easy"?e.weight+e.step:all&&ef==="hard"?Math.max(0,e.weight-e.step):e.weight;return `<div class="card"><div class="exerciseTop"><div class="exerciseTitle"><span class="icon">${e.icon}</span><div><strong>${i+1}. ${e.name}</strong><small>${e.note}</small></div></div><div class="weight"><b>${fmt(e.weight)}kg</b><small>${e.reps}回 × ${e.sets}</small></div></div><div class="sets">${Array.from({length:e.sets},(_,j)=>`<button class="set ${session.sets[e.id][j]?"on":""}" data-set="${e.id}|${j}">${j+1}セット ${session.sets[e.id][j]?"✓":e.reps+"回"}</button>`).join("")}</div><div class="efforts">${[["easy","余裕"],["good","ちょうど"],["hard","きつい"]].map(a=>`<button class="effort ${ef===a[0]?"on":""}" data-eff="${e.id}|${a[0]}">${a[1]}</button>`).join("")}</div><div class="next"><span>次回の目安</span><b>${fmt(next)}kg</b></div></div>`}).join("");
document.querySelectorAll("[data-set]").forEach(b=>b.onclick=()=>{const [id,j]=b.dataset.set.split("|");session.sets[id][+j]=!session.sets[id][+j];if(session.sets[id][+j])startTimer();renderToday()});document.querySelectorAll("[data-eff]").forEach(b=>b.onclick=()=>{const [id,v]=b.dataset.eff.split("|");session.efforts[id]=v;renderToday()});document.querySelectorAll("[data-special]").forEach(b=>{const k=b.dataset.special;b.classList.toggle("on",session[k]);b.textContent=session[k]?"完了 ✓":"完了";b.onclick=()=>{session[k]=!session[k];renderToday()}});cardioDone.textContent=session.cardio?"有酸素 完了 ✓":"有酸素を完了";cardioDone.onclick=()=>{session.cardio=!session.cardio;renderToday()};progress()}
function progress(){const ts=state.exercises.reduce((a,e)=>a+e.sets,0),ds=Object.values(session.sets).flat().filter(Boolean).length,zt=state.zeroi.length,zd=Object.values(session.zeroi).filter(Boolean).length,ex=[session.warmup,session.cardio,session.vibration].filter(Boolean).length,p=Math.round((ds+zd+ex)/(ts+zt+3)*100);ring.style.background=`conic-gradient(var(--accent) ${p*3.6}deg,#262c33 0deg)`;pct.textContent=p+"%"}
function startTimer(){clearInterval(timerI);let n=Number(state.goals.restSeconds)||60;timer.classList.remove("hidden");timerN.textContent=n;timerI=setInterval(()=>{timerN.textContent=--n;if(n<=0){clearInterval(timerI);timer.classList.add("hidden");navigator.vibrate?.([150,80,150]);toast("休憩終了")}},1000)}timerX.onclick=()=>{clearInterval(timerI);timer.classList.add("hidden")};
document.querySelectorAll("[data-cardio]").forEach(b=>b.onclick=()=>{document.querySelectorAll("[data-cardio]").forEach(x=>x.classList.toggle("active",x===b));session.cardioType=b.dataset.cardio;walkPane.classList.toggle("active",session.cardioType==="walk");bikePane.classList.toggle("active",session.cardioType==="bike")});
saveWorkout.onclick=()=>{const done=state.exercises.map(e=>({id:e.id,name:e.name,weight:e.weight,reps:e.reps,setsDone:session.sets[e.id].filter(Boolean).length,effort:session.efforts[e.id]||""})).filter(e=>e.setsDone);if(!done.length){toast("筋トレを1種目以上記録してください");return}state.history.unshift({id:Date.now(),date:new Date().toISOString(),zeroi:state.zeroi.filter(z=>session.zeroi[z.id]).map(z=>({id:z.id,name:z.name,reps:z.reps})),warmup:session.warmup,cardio:session.cardio,cardioType:session.cardioType,vibration:session.vibration,exercises:done});state.exercises.forEach(e=>{if(!session.sets[e.id].every(Boolean))return;const ef=session.efforts[e.id];if(ef==="easy")e.weight+=e.step;if(ef==="hard")e.weight=Math.max(0,e.weight-e.step)});state.configured=true;save();session=newSession();renderToday();toast("保存しました")};
function renderHistory(){const ym=new Date().toISOString().slice(0,7),m=state.history.filter(h=>h.date.slice(0,7)===ym).length,sets=state.history.reduce((a,h)=>a+h.exercises.reduce((b,e)=>b+e.setsDone,0),0);historySummary.innerHTML=`<div class="card"><b>${m}</b><small>今月</small></div><div class="card"><b>${state.history.length}</b><small>累計</small></div><div class="card"><b>${sets}</b><small>総セット</small></div>`;historyList.innerHTML=state.history.length?state.history.map(h=>{const d=new Date(h.date);return `<div class="card"><div class="row"><div><strong>${d.getFullYear()}/${d.getMonth()+1}/${d.getDate()}</strong><small>${h.cardio?(h.cardioType==="bike"?"バイク":"ウォーキング")+"20分":"有酸素未完了"}</small></div><b>${h.exercises.reduce((a,e)=>a+e.setsDone,0)} set</b></div><div class="historyDetail">${h.zeroi?.length?`<div><span>ZERO-i</span><b>${h.zeroi.length}/4種</b></div>`:""}${h.exercises.map(e=>`<div><span>${e.name}</span><b>${fmt(e.weight)}kg × ${e.setsDone}</b></div>`).join("")}</div></div>`}).join(""):`<div class="card muted">まだ履歴がありません。</div>`}
function renderBody(){bodyDate.value=new Date().toISOString().slice(0,10);const a=[...state.body].sort((x,y)=>y.date.localeCompare(x.date));bodyList.innerHTML=a.map(x=>`<div class="card bodyRow"><div class="row"><strong>${x.date.replaceAll("-","/")}</strong><button class="sub" data-delbody="${x.date}">削除</button></div><div class="details"><span>体重 <b>${fmt(x.weight)}kg</b></span><span>脂肪 <b>${fmt(x.fat)}%</b></span><span>筋肉 <b>${fmt(x.muscle)}kg</b></span>${x.waist!=null?`<span>腹囲 <b>${fmt(x.waist)}cm</b></span>`:""}</div></div>`).join("");document.querySelectorAll("[data-delbody]").forEach(b=>b.onclick=()=>{state.body=state.body.filter(x=>x.date!==b.dataset.delbody);save();renderBody()});drawChart()}
bodyForm.onsubmit=e=>{e.preventDefault();const x={date:bodyDate.value,weight:+bodyWeight.value,fat:bodyFat.value?+bodyFat.value:null,muscle:bodyMuscle.value?+bodyMuscle.value:null,waist:bodyWaist.value?+bodyWaist.value:null};state.body=state.body.filter(y=>y.date!==x.date);state.body.push(x);state.configured=true;save();e.target.reset();renderBody();toast("追加しました")};metric.onchange=drawChart;window.addEventListener("resize",()=>{if(document.getElementById("body").classList.contains("active"))drawChart()});
function drawChart(){const key=metric.value,c=chart,ctx=c.getContext("2d"),w=c.clientWidth,h=220,dpr=devicePixelRatio||1;c.width=w*dpr;c.height=h*dpr;ctx.scale(dpr,dpr);ctx.clearRect(0,0,w,h);let a=[...state.body].sort((x,y)=>x.date.localeCompare(y.date)).filter(x=>x[key]!=null);ctx.strokeStyle="#2d343c";for(let i=0;i<5;i++){let y=20+i*(h-45)/4;ctx.beginPath();ctx.moveTo(18,y);ctx.lineTo(w-12,y);ctx.stroke()}if(!a.length){ctx.fillStyle="#98a2ad";ctx.fillText("データなし",20,40);return}const v=a.map(x=>x[key]),mn=Math.min(...v),mx=Math.max(...v),pad=Math.max((mx-mn)*.25,key==="weight"?1:.5),lo=mn-pad,hi=mx+pad,X=i=>a.length===1?w/2:22+i*(w-44)/(a.length-1),Y=n=>h-28-(n-lo)/(hi-lo)*(h-54);ctx.strokeStyle="#a8ef70";ctx.lineWidth=3;ctx.beginPath();a.forEach((x,i)=>i?ctx.lineTo(X(i),Y(x[key])):ctx.moveTo(X(i),Y(x[key])));ctx.stroke();a.forEach((x,i)=>{ctx.fillStyle="#a8ef70";ctx.beginPath();ctx.arc(X(i),Y(x[key]),4,0,Math.PI*2);ctx.fill();ctx.fillStyle="#e8ecef";ctx.font="11px sans-serif";ctx.textAlign="center";ctx.fillText(fmt(x[key]),X(i),Y(x[key])-9);ctx.fillStyle="#7f8994";ctx.fillText(x.date.slice(5).replace("-","/"),X(i),h-8)})}
function renderSettings(){goalWeight.value=state.goals.weight??"";goalFat.value=state.goals.fat??"";goalMuscle.value=state.goals.muscle??"";restSec.value=state.goals.restSeconds||60}
saveSettings.onclick=()=>{state.goals={weight:goalWeight.value?+goalWeight.value:null,fat:goalFat.value?+goalFat.value:null,muscle:goalMuscle.value?+goalMuscle.value:null,restSeconds:+restSec.value||60};state.configured=true;save();toast("設定を保存しました")};
exportBtn.onclick=()=>{const blob=new Blob([JSON.stringify(state,null,2)],{type:"application/json"}),a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download=`gym-note-backup-${new Date().toISOString().slice(0,10)}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)};
importFile.onchange=async e=>{const f=e.target.files[0];if(!f)return;try{state=migrate(JSON.parse(await f.text()));save();session=newSession();renderToday();toast("データを読み込みました")}catch(err){toast("JSONを読み込めませんでした")}e.target.value=""};
resetBtn.onclick=()=>{if(confirm("この端末内の履歴・身体データを初期化しますか？")){state=clone(TEMPLATE);save();session=newSession();renderToday();toast("初期化しました")}};
window.addEventListener("beforeinstallprompt",e=>{e.preventDefault();installPrompt=e;installBtn.hidden=false;installBtn.onclick=async()=>{installPrompt.prompt();await installPrompt.userChoice;installBtn.hidden=true;installPrompt=null}});
async function registerSW(){if(!("serviceWorker" in navigator))return;try{const r=await navigator.serviceWorker.register("./sw.js");checkUpdate.onclick=async()=>{await r.update();toast("更新を確認しました")}}catch(e){}}window.addEventListener("load",registerSW);renderToday();